Update sub.yml

diff --git a/.github/workflows/sub.yml b/.github/workflows/sub.yml
--- a/.github/workflows/sub.yml
+++ b/.github/workflows/sub.yml
@@ -124,7 +124,7 @@ jobs:
       - name: Setup KernelSU
         run: |
           cd KernelSU-Next/kernel
-          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-dev || { echo "Failed to run setup.sh"; exit 1; }
+          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next || { echo "Failed to run setup.sh"; exit 1; }
           git submodule update --init --recursive || { echo "Failed to initialize submodules"; exit 1; }
           KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
           echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
