Update sub.yml

diff --git a/.github/workflows/sub.yml b/.github/workflows/sub.yml
--- a/.github/workflows/sub.yml
+++ b/.github/workflows/sub.yml
@@ -108,22 +108,20 @@ jobs:
         run: |
           git clone https://github.com/KernelSU-Next/KernelSU-Next.git --branch next --depth=1 || { echo "Failed to clone KernelSU-Next"; exit 1; }
 
-      - name: Verify KernelSU-Next Directory Structure
+      - name: Integrate KernelSU-Next into Kernel Source
         run: |
-          cd KernelSU-Next
-          if [ ! -d "kernel" ]; then
-            echo "Error: 'kernel/' directory not found in KernelSU-Next repository."
-            exit 1
-          fi
+          cd kernel_platform/oneplus13r_v
+          cp -r ../KernelSU-Next/kernel/* ./kernel_platform/oneplus13r_v/kernel/ || { echo "Failed to copy KernelSU-Next files"; exit 1; }
 
       - name: Setup KernelSU
         run: |
-          cd KernelSU-Next/kernel
-          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-dev || { echo "Failed to run setup.sh"; exit 1; }
+          cd kernel_platform/oneplus13r_v/kernel
+          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs || { echo "Failed to run setup.sh"; exit 1; }
           git submodule update --init --recursive || { echo "Failed to initialize submodules"; exit 1; }
           KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
           echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
           sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
+     
     
       - name: Setup SUSFS
         run: |
